language: cpp
os:
  - linux
compiler:
  - g++
install:
  - sudo pip install codecov 
script: # -C parameter is for MakefileDir
  - make 
  - make test
  - make gcov # remember to add gcov flag in Makefile
branches:
  only:
    - master
after_success:
  - codecov -t 37864c49-beaa-4739-ad27-bd053302f629 -X gcov
